# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 12:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('restaurant', '0001_initial'), ('restaurant', '0002_auto_20160318_1523'), ('restaurant', '0003_auto_20160318_1525'), ('restaurant', '0004_auto_20160320_1800'), ('restaurant', '0005_auto_20160320_2316'), ('restaurant', '0006_auto_20160320_2320'), ('restaurant', '0007_auto_20160320_2357'), ('restaurant', '0008_auto_20160321_1426'), ('restaurant', '0009_restaurant_second_pnumber'), ('restaurant', '0010_restaurant_is_active')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingerents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MenuPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ingerents', models.ManyToManyField(max_length=128, to='restaurant.Ingerents')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=128)),
                ('ratings', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.MenuPosition')),
                ('rate_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=128)),
                ('slug', models.SlugField(default=datetime.datetime(2016, 3, 21, 14, 26, 45, 58933, tzinfo=utc), max_length=128, unique=True)),
                ('second_pnumber', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(1, 'Mała'), (2, 'Średnia'), (3, 'Duza')], default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.MenuPosition')),
            ],
        ),
        migrations.AddField(
            model_name='menuposition',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together=set([('name', 'size')]),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('meal', 'rate_by')]),
        ),
        migrations.AlterField(
            model_name='ingerents',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterModelOptions(
            name='ingerents',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name', 'size']},
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='ingerents',
            field=models.ManyToManyField(blank=True, max_length=128, to='restaurant.Ingerents'),
        ),
        migrations.AddField(
            model_name='menuposition',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 3, 21, 14, 26, 31, 250991, tzinfo=utc), max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
