# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_squashed_0010_restaurant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='test',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
