# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='tel',
            new_name='phone_number',
        ),
    ]
