# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20160318_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingerents',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
