# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20160414_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='test',
        ),
    ]
