# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20160318_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingerents',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name', 'size']},
        ),
        migrations.AddField(
            model_name='menuposition',
            name='rate',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
