# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20160320_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuposition',
            name='rate',
        ),
        migrations.AlterField(
            model_name='rating',
            name='ratings',
            field=models.PositiveIntegerField(),
        ),
    ]
