# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20160320_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuposition',
            name='ingerents',
            field=models.ManyToManyField(blank=True, max_length=128, to='restaurant.Ingerents'),
        ),
    ]
