# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20160320_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuposition',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 3, 21, 14, 26, 31, 250991, tzinfo=utc), max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 3, 21, 14, 26, 45, 58933, tzinfo=utc), max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
