# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20160321_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='second_pnumber',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
