# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_restaurant_second_pnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
