# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_squashed_0006_auto_20160324_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
