# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='closed',
        ),
    ]
