# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20160324_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.CharField(max_length=50),
        ),
    ]
